### ISSUE TITLE
Build a mock 26-1880 form

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#103]
### Background
As a member of the AEDP team, I want to have a mock 26-1880 form so that i can test a variety of scenarios with users.

There exists a new proposed version of the review page styling as seen below. We believe that using this new version, both at the end of the form and during the editing step, will help users to have a more seamless user experience and use less energy to complete tasks.

Moving to replace the 'address' component with this new component will also help to reduce design debt and improper component usage.

![Image](https://github.com/user-attachments/assets/eaa178a1-d74d-4c27-a3c3-67556c67dd19)

### ACs
- [x] The 26-1880 form has been recreated in staging

**Comment by adamwhitlock1** [comment]
Assigning to myself to even the load a bit for this sprint, and assigning #105 to Belle. That way we each have a spike task and larger task to work on this sprint.

**Comment by adamwhitlock1** [comment]
I went through the experimental designs for the review page work and talked with Jeanna about the current state of the review page prototypes.

This new review page has _not_ been coded out yet, and the current state of the design will be going through midpoint review and then usability research. Estimate is 6 weeks before any of that gets started and then engineering will work on some tech debt on the 20-10206 so that they can fork it to work on as an example form that covers most of the use cases.

@msbtterswrth should we just close this out then since there is no current version of the new review page in the code yet?

The 26-1880 form is current up in staging at the url: https://staging.va.gov/mock-form-ae-design-patterns/2/task-red

**Comment by msbtterswrth** [comment]
@adamwhitlock1 could you let me know a good staging user to test with? 

Also was Jeanna saying we can't _also_ test out the new design? I know it's not been fully tested yet but I was hoping we could use it and do our own testing on it as well. I don't really want to be building a pattern based on something we know is about to change soon. 

For the purposes of this task however, I think we can call it done and then move the review page/step ACs into a task for next sprint.

**Comment by adamwhitlock1** [comment]
You should be able to test in staging with basically any user, but I was able to see the form with `vets.gov.user+226@gmail.com`

Maybe we can discuss the review page more during sprint planning today and come up with a good way forward. 

I think there is the possibility of it changing, but also it is not available to use in the code at all yet, so we would be building the UI and implementing it within the form system ourselves from scratch first before being able to use it for testing.
