### ISSUE TITLE
Draft content for pattern guidance

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#109]
This task has been split from #67, since we needed to extend our study.

We need to draft the actual content including mockups for VADS contribution based on our research study. 

### ACs
- [x] Content has been drafted for the VADS page including
    - [x] What the pattern is and is not
    - [x] Usage Guidelines
    - [x] How to design an build
    - [x] Content Considerations
    - [ ] Examples
- [ ] Draft has been reviewed by Internal Team

**Comment by msbtterswrth** [comment]
Our draft guidance can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/patterns/prefill/Help-users-to-Know-when-their-information-is-prefilled.md

**Comment by msbtterswrth** [comment]
@ChristineRoseSteiffer when you come back tomorrow, could you review and update this page? I have added the annotaged designs, the how to design and build sections and links to our research.

**Comment by ChristineRoseSteiffer** [comment]
I think this looks pretty good so far @msbtterswrth - thanks for your help moving this forward! @beckyphung we'd love to get your eyes on this for a review. If you have time before our Monday meeting next week to look at it, we could use some of that time to discuss. Thanks!

**Comment by beckyphung** [comment]
@ChristineRoseSteiffer @msbtterswrth I was OOO Friday, so I'm reviewing this today.

**Comment by beckyphung** [comment]
Added some of my notes in [this Slack thread](https://dsva.slack.com/archives/C07909N7U8Z/p1727102660825649). 

Complete summary of my feedback/updates here though: 
### Updates I made
- Update titles to use [sentence case](https://design.va.gov/content-style-guide/capitalization)
- Added links usually found at the top of VADS paterns (ex: jump links, resources section...)
- Reworded the `Authenticated review alert` to `Authenticated contextual alert` because it might get confused with the review page
- Edited some content to use active voice
- Added more details to the **Anatomy or layout details** section
- Added image captions

### Needed before closing this 
- @msbtterswrth Do you want to review the updates I made in a call? Or async? 
- [ ] Add image to [Unauthenticated introduction page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/patterns/prefill/Help-users-to-Know-when-their-information-is-prefilled.md#unauthenticated-introduction-page)
- [ ] Add image caption to [Unauthenticated introduction page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/patterns/prefill/Help-users-to-Know-when-their-information-is-prefilled.md#unauthenticated-introduction-page)
- [ ] Add guidance for [Directions for updating uneditable information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/patterns/prefill/Help-users-to-Know-when-their-information-is-prefilled.md#directions-for-updating-uneditable-information)

### Questions 
- Where do we tell the user where their data is coming from? In our pattern, we say... "It is crucial to explain to the user exactly where the data is coming from so that if there are any errors in the data, it is clear how to correct them." Is it when we reference "the account" in our content guidance?

### Potential next steps I'm thinking of (outside of this particular ticket)
- [ ] Review content with Laura from CAIA (I think she's our assigned person)
- [ ] Get feedback from VFS teams in some way (at least 1 person... async or in a call)
- [ ] Review with Matt

### Other
- Not including "prefill" in the title as Matt suggested to be less jargony. However, if we want the page to be findable via search, then adding "prefill" to the title might make it easier to find because we use "prefill" in the body of many VADS pages anyway

**Comment by msbtterswrth** [comment]
I've added the image and captions, but re

> Add guidance for [Directions for updating uneditable information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/patterns/prefill/Help-users-to-Know-when-their-information-is-prefilled.md#directions-for-updating-uneditable-information)

This text is currently being rewritten by CAIA per #101.

**Comment by beckyphung** [comment]
**Unauthenticated introduction page**
I'm not seeing the image for the `Unauthenticated introduction page` 
![Image](https://github.com/user-attachments/assets/e7ad8315-a190-43d4-9c3a-1c1c9da2d19f)

**Directions for updating uneditable information**
We can still give guidance on using the existing content though. From my understanding:
- If it's benefits related, include the content that has the VA benefits hotline
- If it's health related, include the content that has the VA benefits hotline AND the content to contact your local medical center

This is a variation that people are already doing, but isn't explicit in the pattern. 

**Keeping prefill in the title**
Ok, noted for Matt

**Review** 
It would be helpful to review this before closing with Christine if there's time today.

**Comment by msbtterswrth** [comment]
Ah apologies, I left the heading, but I merged the intro page back under one heading with two subheads, as this is the same form content, just different alerts based on authentication state.

![Image](https://github.com/user-attachments/assets/55d0eaba-ec14-4fc1-882e-392bcbf526c2)

**Comment by beckyphung** [comment]
Ok I see it now. So based on current guidance for the unauthenticated sign in alert, it shouldn't be at the top of the page. It should be lower. See [form intro page template in VADS](https://design.va.gov/templates/forms/introduction#unauthenticated).

**Comment by beckyphung** [comment]
@msbtterswrth Before I close this, I'd like to add the remaining follow-up steps and questions from this issue to the "finalize" issue in Sprint 8. I don't think I see it created yet. Could you direct me to it if I'm just missing it or link to it here?

**Comment by msbtterswrth** [comment]
The task for finalizing this content is #119, we can def take care of ironing these things out there.

**Comment by beckyphung** [comment]
Thanks Lynn. Updating the ACs in #119 to address remaining questions here. Closing now.
