### ISSUE TITLE
Investigate adding markup/markdown styling to VADS for code snippets

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#185]
### Background 
As we updated our VADS page with code examples, we noticed that there wasn't much visually distinguishing it from regular text. 

![Image](https://github.com/user-attachments/assets/baf3cff9-4aa3-414a-b1f2-43e93facf19d)

After [discussing this with the design system folks](https://dsva.slack.com/archives/C01DBGX4P45/p1730480985232439) we have the go ahead to investigate adding some kind of codeblock styling similar to something like this.

![Image](https://github.com/user-attachments/assets/500b4ee9-ab64-4e54-a891-4fc998f606c6)

There may be a way to add markdown or syntax styling into the jekyll templates or we may need to roll our own, let's investigate.

### ACs
- [ ] Codeblocks can be styled in VADS pages

**Comment by adamwhitlock1** [comment]
[Configuring syntax highlighting within markdown and Jekyll](https://jekyllrb.com/docs/configuration/markdown/#syntax-highlighting-coderay) looks to be relatively painless by using Coderay

Coderay would be the most universal way to go about it because then any markdown that uses code blocks would be styled. Alternativesly there is also a way to [use Rouge](https://jekyllrb.com/docs/liquid/tags/#code-snippet-highlighting) but that requires code blocks to be surrounded by a specific liquid tag:


```
{% highlight ruby %}
def foo
  puts 'foo'
end
{% endhighlight %}
```

We will also need to figure out the best styling / theme to use for our code block sections.

**Comment by adamwhitlock1** [comment]
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3507

PR is in review when it merges I'll let yall know. Preview the work here: https://dev-design.va.gov/3507/patterns/help-users-to/know-when-their-information-is-prefilled

**Comment by msbtterswrth** [comment]
This is amazing!! Excellent work!
