### ISSUE TITLE
Update prefill pattern VADS content

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#253]
[Staging review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98543) feedback on our new pattern:
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/98539 - BLOCKER
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/98543 (make changes to https://dev-design.va.gov/3480/content-style-guide/error-messages/engagement) **See comment below with the updates needed for this bullet point.**
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/98540
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/98541
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/98542
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/98532
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/98534

[Staging review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98543) feedback on our the [Prefill pattern documentation](https://design.va.gov/patterns/help-users-to/know-when-their-information-is-prefilled):
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/98533
   - [x] Change the sentence "When using this pattern, clearly inform the user of where their data is being pulled from to prefill for them." to "When using this pattern, clearly inform the user where their data is being pulled from to complete the prefill."
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/98534
   - [x] The "Design Principles" section should use the exact text that we have in the [Update Prefill page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/Patterns/update-prefilled-information/Help%20users%20to%20update%20prefilled%20information.md). 
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/98535
   - [x] In the caption "Image caption: Editable prefilled information displayed on the Prefill check page. This is the proposed style to display data that is editable" make "prefill" lower case.
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/98536
  - [x] In the bullet point "Directions for editing uneditable information" remove the last phrase "which will be updated soon".

Additional changes to make to the [Prefill pattern](https://design.va.gov/patterns/help-users-to/know-when-their-information-is-prefilled) based on the changes we made after the second round of research:

USAGE section
- [x] In "When not to use this pattern > For unauthenticated users" the period after "unauthenticated users" should be bolded to match other bolded periods on the page.

HOW TO DESIGN AND BUILD section
- [x] Change "Prefill check page: Any page of a form that displays prefilled information users can edit within the form." to say "Prefill edit pages: Any pages on which users edit prefilled data."
- [x] Update screenshots under the "How to design and build" - see Slack message
- [x] "How this pattern works" section - use [what we have in Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/Patterns/update-prefilled-information/Help%20users%20to%20update%20prefilled%20information.md#how-this-pattern-works) for this section (I had updated it earlier but we didn't make a PR with it)
- [x] Under "How this pattern works," after the sentence "The alert also encourages users to sign in to benefit from this time-saving feature." add "This alert should be placed at the top of the page, directly under the form name."

EXAMPLES section
I think most of this requires updates to the code. 
- [ ] Update cards to match designs
- [x] Remove the Prefilled Info Alert
- [ ] Update Signed In Prefill Alert to match designs

CONTENT CONSIDERATIONS section
- [x] Under "Directions for updating uneditable information" change the text to: "Directions for updating information that can’t be updated online vary. See the ["Help users to... Update Prefilled information" pattern](https://design.va.gov/patterns/help-users-to/update-prefilled-information) for guidance.
- [x] Replace "Authenticated intro page alert" screenshot - see Slack message
- [x] Remove the "Authenticated contextual alert" header, text, and screenshot below it.

RESEARCH section
- [x] Update the user research section to say: "The Authenticated Experience Design Patterns team conducted [user research](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/authenticated-patterns/Design%20and%20Research/2024-07-Research%20Initiative-One-Prefill) in mid 2024 to gather validation about this pattern. The pattern was [further tested](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/Design-and-research/2024-09-Research-Initiative-Two-Update-Prefill/Update%20Prefill%20Research%20Report.md) as part of a late 2024 study by the same team.

[Staging review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98543) feedback on the "[Help users to…Know how their information is updated](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated)" pattern, which will be coming down (no action needed; we'll close the tickets):
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/98537
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/98538

**Comment by msbtterswrth** [comment]
@kristen101606 @ChristineRoseSteiffer can we drop in the updates that need to be made for the first pattern including screenshots and content that needs to be updated.

**Comment by adamwhitlock1** [comment]
The main content PR for this page is marked as ready to review here:

https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3562

Everything but the code examples for the 'Know when their information is prefilled' have been updated to what is the newest content and addresses these staging tickets.

@msbtterswrth there has been a lot of back and forth for the content, and I am 95% sure that I have all the current changes integrated into this PR, but if you could double check my work, the preview URL is: https://dev-design.va.gov/3562/patterns/help-users-to/update-prefilled-information

**Comment by kristen101606** [comment]
For the second bullet point in the body of the comment above, here are the changes we need to make: 

- On the [Engagement messages page](https://design.va.gov/content-style-guide/error-messages/engagement#prompt-to-complete-a-task-or-enter-data), there are 3 rows that deal with Prefill. Those 3 rows should change to these 2 rows: 

| Scenario    | Message title | Message content | Actions | Component | State | Location |
| -------- | ------- | ------- | ------- | ------- | ------- | ------- |
| Prefill - Intro variation (for authenticated users) | We’ve prefilled some of your  information | Since you’re signed in, we’ve prefilled part of your application based on your profile details. You can also save your application in progress and come back later to finish filling it out. | None | [Alert box](https://design.va.gov/components/alert) | [Informational](https://design.va.gov/components/alert/#examples---standard) | After h1 on [Form Introduction page](https://design.va.gov/templates/forms/introduction) |
| Prefill - Step variation (for authenticated users) - If saving to form and Profile | None | Any changes you make will also be reflected on your VA.gov profile. | None | [Alert box](https://design.va.gov/components/alert) | [Informational](https://design.va.gov/components/alert/#examples---standard) | After [Progress bar - Segmented](https://design.va.gov/components/form/progress-bar-segmented) on a [Form Step page](https://design.va.gov/templates/forms/form-step) | 


- On the [System Messages page](https://design.va.gov/content-style-guide/error-messages/system#updates-to-user-data-system-initiated), we should replace the row starting with "Form prefill notice" to the below 2 rows:

| Scenario    | Message title | Message content | Actions | Component | State | Location |
| -------- | ------- | ------- | ------- | ------- | ------- | ------- |
| Save your work in progress (for unauthenticated users) | Sign in now to save time and save your work in progress | Here’s how signing in now helps you: * We can fill in some of your information for you to save you time. * You can save your work in progress. You’ll have 60 days from when you start or make updates to your application to come back and finish it. **Note:** You can sign in after you start your application. But you’ll lose any information you already filled in. | Sign in to start your application (primary button); Start your application without signing in (link) | [Alert box](https://design.va.gov/components/alert) | [Informational](https://design.va.gov/components/alert/#examples---standard) | After h1 on [Form Introduction page](https://design.va.gov/templates/forms/introduction) |
| Prefill - Intro variation (for authenticated users) | We’ve prefilled some of your  information | Since you’re signed in, we’ve prefilled part of your application based on your profile details. You can also save your application in progress and come back later to finish filling it out. | None | [Alert box](https://design.va.gov/components/alert) | [Informational](https://design.va.gov/components/alert/#examples---standard) | After h1 on [Form Introduction page](https://design.va.gov/templates/forms/introduction) |

**Comment by msbtterswrth** [comment]
@adamwhitlock1 this looks great to me! Let's get this in front of Matt and co and we'll address any changes we need to make next sprint in a separate PR.
