### ISSUE TITLE
Determine what we're testing and how

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#56]
### Background
As an AEDP team member I want to know what we're testing within the **Update prefilled information** pattern https://github.com/department-of-veterans-affairs/tmf-auth-exp-design-patterns/issues/22 and how we're going to test it so I can create a research plan and prototypes.

### ACs
- [x] An outline of the problems exist for **Update prefilled information** along with how we might solve them
- [x] We have determined as a team how to test our hypotheses
- [x] Team has reviewed and agreed on hypotheses and tests

**Comment by msbtterswrth** [comment]
As part of #55 we created a discovery mural that includes our hypotheses and testing methodology: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1722538963593/ec6a1e4d13493cc9fbb07898a31120cec2bf69c0?sender=u11b5f7711188298523d03159.

**Comment by ChristineRoseSteiffer** [comment]
I have put together a document that summarizes what we are testing and how we got to that decision. It is in [google](https://docs.google.com/document/d/17RNjPTr30Csl6xvcbmcEkmReVtL5LABxlKuDAGvz6S4/edit?usp=sharing) for now, but will be updated to GitHub after review from the team.

**Comment by msbtterswrth** [comment]
This looks really great to me!

**Comment by beckyphung** [comment]
@msbtterswrth or @ChristineRoseSteiffer A couple questions I have: 
- I see the **An outline of the problems exist along with how we might solve them** AC is checked off. What are we considering as the 'outline'? Can someone add a link to this outline? 
- How are we logistically going to **...determine as a team how to test our hypotheses**? Ex: Are we going to decide after a certain meeting, after getting the whole team to review something, etc. How do we verify that the team is on board with what we're testing
- Should another ticket be created for Christine's doc? Since this ticket is for the **Update prefilled information** pattern, and Christine's doc is for **Know how their information is prefilled**

**Comment by msbtterswrth** [comment]
I'm  considering our [discovery mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1722538963593/ec6a1e4d13493cc9fbb07898a31120cec2bf69c0?sender=u11b5f7711188298523d03159) the artifact for this task. In it we have outlined several main pain points, or problems with current implementations of this or related patterns:
- Users are unsure where their updates will save to, and don't trust that the VA will update them in the right place
- Users don't understand why they cannot edit some information
- Users don't have a consistent method for actually updating their prefilled information, as many forms  implement this differently
- Users aren't able to review their information before they update it

![Image](https://github.com/user-attachments/assets/d4c1ba61-77ac-44f2-8a2c-97ce60071bf5)


We also have documented four main facets, or outcomes of this pattern and how we can test those hypotheses:
- users will know why they can't update some information
- users will know how to update their information
- users will know how to review their information as they're updating it
- users will know where their updated information is saved to 

![Image](https://github.com/user-attachments/assets/5f5e99f4-5537-43d7-aaa3-236d97f15d92)

I think we can move christine's doc to our va.gov-team's repo but create a similar one for this pattern, which would be the deliverable for #58

**Comment by beckyphung** [comment]
Ok outline is clear now. I don't think we should mark off the 'team review' AC yet, since: 
- We haven't met during our product sync for a review together yet. I have some questions. 
- The team won't be able to review a final version until we meet. 

I still have this question:
> How are we logistically going to ...determine as a team how to test our hypotheses? Ex: Are we going to decide after a certain meeting, after getting the whole team to review something, etc. How do we verify that the team is on board with what we're testing

> I think we can move christine's doc to our va.gov-team's repo but create a similar one for this pattern, which would be the deliverable for https://github.com/department-of-veterans-affairs/tmf-auth-exp-design-patterns/issues/58
Let's discuss this during our product sync too

**Comment by beckyphung** [comment]
During product sync, @msbtterswrth mentioned she would:
- Add an AC for team review and what that looks like. 

I'm good with moving Christine's doc into our folder in the va.gov-team repo for the "Know when their information is prefilled" pattern. 

@msbtterswrth and I are planning on meeting tomorrow, since we didn't get a chance to review the board in depth during product sync today.

**Comment by msbtterswrth** [comment]
We met today as a team and discussed our baseline understandings and how we plan to test them. We have agreed to test:
- telling users where this form will save to
    - via alert
    - some other help text or component
- telling users their update was successful
    - via alert at top of page
    - via success indication per field
- helping users to edit prefilled information
    - testing preference for autofilled fields during edit
    - showing the profile subheader during edit screen
    - using new 'review page' layout for prefilled information
- telling users why they can't update
    - via alert
    - some other help text or component
    - include a link to a page for more information
