### ISSUE TITLE
Draft design variations

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#59]
### User Story
As a member of the AEDP I want to draft the variations we are testing for this pattern so that the engineering team can begin to build the prototypes in staging.

### ACs
- [x] Forms have been decided on
- [x] Figma page is set up with the chosen forms 
- [x] A design has been created that provides a UX for how to ask "where would you like this information saved"
- [x] Figma contains draft variations 
- [x] Internal Team review of drafts is complete 

### Artifacts
- [Figma Design Files for Update Prefill](https://www.figma.com/design/1z3bAkQl4uR1IvAxmtyqZi/AE-Design-Patterns---Update-Prefill?t=CfAQF9SqMe7qQ1BP-0)

### Forms we are testing
- 22-1880 - Apply for VA Education Benefits
- 22-1990 - Request a VA Home Loan Certificate of Eligibility (COE)
- 10182 - Request a Board Appeal

**Comment by ChristineRoseSteiffer** [comment]
I can get this task started this sprint but with those ACs it will need to get carried over to next sprint. We could also split it up. Please advise @msbtterswrth - thanks!

**Comment by ChristineRoseSteiffer** [comment]
The draft designs are compiled for the team's review (see link in ticket description above). Planning to go over them during today's team call. I'm proposing passing these designs over to our new designer @kristen101606 to finalize next sprint so that I can focus on the research documentation. 

Last week, we finalized the selection of forms after we got a list from Matt of forms that use the unauthenticated prefill alert on their Intro page. I have posted the final selection in the ticket description above. 

We also met with both the Non-Disability Benefits team and the Veteran Facing Forms team to discuss their forms and work related to our Update Prefill work. Their work is relevant to the forms we are testing this round. We will work closely with these teams as we build out our prototype to ensure cross-team collaboration for this work.

**Comment by ChristineRoseSteiffer** [comment]
We reviewed the draft design files together today as a team, and I made some notes with suggestions from the team to the files directly. This ticket is ready for PO review. Any suggested updates to the designs will be covered in our Finalize Designs ticket (#61) during next sprint.

**Comment by beckyphung** [comment]
I added some questions to the Figma file at the bottom. Looks like it's still a WIP, so maybe the next iteration will answer some of my questions too

**Comment by ChristineRoseSteiffer** [comment]
Thanks for your questions! Yes this is still in draft form. We'll need to work out the exact test plan next sprint and they will be cleaned up accordingly. I've added the note about testing the different language options for updating locked data.
