### ISSUE TITLE
Draft research plan

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#60]
### User Story
As a member of the AEDP team I want to begin drafting our research plan so that our PO has time to review and provide input before we submit it.

This research plan is for #22 Help users to... Update prefilled information. 

### ACs
- [x] A first draft of [our research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/Design%20and%20Research/2024-09%20Research%20Initiative%202%20-%20Update%20Prefill/draft%20research%20plan.md) exists
- [x] A first draft of our conversation guide exists

**Comment by msbtterswrth** [comment]
I have begun a [draft research doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/Design%20and%20Research/2024-09%20Research%20Initiative%202%20-%20Update%20Prefill/draft%20research%20plan.md) for our next study. 

We'll need to fill out information about what we're testing and our scheduling/methodology.

**Comment by msbtterswrth** [comment]
@ChristineRoseSteiffer do you think you'll have time to review this draft this sprint? We do NOT need to have final content, there is another task next sprint.

**Comment by ChristineRoseSteiffer** [comment]
@msbtterswrth I think we can call this ticket done for this sprint. We have a shell of a draft. As we make some decisions around what exactly our test prototype will look like, we can update the plan accordingly with a future ticket.

**Comment by beckyphung** [comment]
I'll try to review this by EOD

**Comment by beckyphung** [comment]
See my thoughts on each of these research goals below. I went through each one and tried to understand the purpose for each goal. Please lmk if this aligns with what you were thinking too @msbtterswrth and @ChristineRoseSteiffer 

### Goal 1: Understand how users expect the prefilled data to display.
- **Related components in our pattern**: Uneditable and editable prefilled information 
- **Purpose**: So we can decide which component users prefer (`gray card` or `white card with outline`) and to recommend in our pattern
- **Why I think we don't need this goal**: There wasn't a overwhelming preference for address block or gray card in the previous study. 
   - `address block` We know address block is out because: (1) it isn't in USWDS which may make it more difficult to contribute, something I've heard Matt mention and (2) using address block in this way would be outside of its original purpose. 
   - `gray card` We know [VADS recommends](https://design.va.gov/components/card#2-default-white) moving away from gray card (similar to other direction we've gotten and won't test, like inline editing).
   - Therefore, I'd recommend we make the decision update [our pattern guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/patterns/prefill/Help-users-to-Know-when-their-information-is-prefilled.md) to using `white card with outline` AND remove this research goal
  
### Goal 2: Understand users' expectations around why certain data can be edited within their profile and other data cannot.
- **Related components in our pattern**: Directions for updating uneditable information 
- **Purpose**: Test new content that has clearer directions and links to and information page on VA.gov ([Danielle's comments in this Slack thread](https://dsva.slack.com/archives/C01K37HRUAH/p1726671696264749?thread_ts=1725474201.909539&cid=C01K37HRUAH))
- **Suggested revision**: Understand if users understand the directions for updating uneditable information 

### Goal 3: Understand if users want or need a confirmation step before submitting forms with prefilled data.
- **Related components in our pattern**: The form review page, I think?
- **Purpose**: I'm actually not sure about the purpose for this. All forms should have a review page. We shouldn't test a form without a review page. What we CAN test is whether reviewing prefilled information once is fine, and omit prefilled info on the review page (which some forms do). OR whether it's a better experience to review prefilled information in the middle of the form AND on the review page (some forms also do this). 

### Goal 4: Understand how users expect the edit process to work and where they expect their edits to get saved.
- **Related components in our pattern**: Confirmation message after saving, Edit as a subtask page with profile banner(?)
- **Purpose**: Test asking people whether they'd like to update their profile or not. If they do want to update their profile, test whether the confirmation message is clear. I'm assuming that their profile would be updated in the middle of the form, before hitting submit at the end.

**Comment by beckyphung** [comment]
Closing this issue. We'll follow up on the above in Sprint 8 in #62
